### ISSUE TITLE
Using items from XML instead of an array in JS file

### ISSUE THREAD

**Issue by sushant-j** [rkhayyat/nativescript-swipe-card#1]
Hello!
I am trying to use this plugin to create a stack of swipeable cards in a project. For the same, is it possible to use `<SwipeCard>` as a normal element instead of a self-closing one? 
The reason is that I have my cards already created in XML, using [nativescript-cardview](https://github.com/bradmartin/nativescript-cardview). The layout is pretty complex, so it would be great if I could just use it as a child of <SwipeCard> element instead of passing an items array as a prop.

Current Implementation:
```
   <customControls:SwipeCard row="1" id="swipe" 
                                  height="70%"
                                  width="100%" 
                                  cardHeight="30"
                                  backgroundColor="green" 
                                  cardWidth="70"
                                  items="{{ cards }}"
                                  isRandomColor="1"
                                  cardBorderRadius="20"
                                  cardBorderWidth="2"
                                  />
```

Implementation wanted:
```
   <customControls:SwipeCard row="1" id="swipe" 
                                  height="70%"
                                  width="100%" 
                                  cardHeight="30"
                                  backgroundColor="green" 
                                  cardWidth="70"
                                  isRandomColor="1"
                                  cardBorderRadius="20"
                                  cardBorderWidth="2"
                                  >
      <nv:CardView>
      <!-- Content of cards -->
     </nv:CardView>
   </customControls:SwipeCard>
```

Also, I'm not exactly sure how I can get multiple `<nv:CardView>` as child elements for the `<SwipeCard>`.

Any help much appreciated!

**Comment by rkhayyat** [comment]
Hello Sushant,
Thanks for your interest, using the swipe-card plugin, however unfortunatly with this plugin, you have to have your stack cards already created and passed as an array to the component.

However, if you wanto pass the CardView as your card, you can use the plugin of my friend Jean-baptiste which you can find it here :)
https://github.com/rhanb/nativescript-swipe-layout

**Comment by sushant-j** [comment]
Thanks for the reply @rkhayyat ! 

I'll try the plugin by @rhanb as you mentioned. Though by the looks of it, it only has Angular/TS implementation, whereas I'm working with Vanilla JS. Any idea if it's supported?

Thanks again for your prompt reply :) This issue can be closed now.

**Comment by rhanb** [comment]
@sushant-j `nativescript-swipe-layout` works with Vanilla JS too, the only thing that changes is the way you bind events to your JS. `(event)="function($event)` in Angular, `event={{ function }}` in Vanilla JS 👍
